apiVersion: v1
kind: Secret
metadata:
  name: postgres-auth-secret
  namespace: microservices
type: Opaque
stringData:
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "1234"
  POSTGRES_DB: "auth_service_dev"
  POSTGRES_HOST: "postgres-auth-service"
  DATABASE_URL: "postgres://postgres:1234@postgres-auth-service:5432/auth_service_dev?sslmode=disable"