apiVersion: v1
kind: Service
metadata:
  name: postgres-auth-service
  namespace: microservices
spec:
  selector:
    app: postgres-auth
  ports:
  - port: 5432
    targetPort: 5432
    protocol: TCP
    name: postgres
  type: ClusterIP