apiVersion: apps/v1
kind: Deployment
metadata:
  name: account-service
  namespace: microservices
spec:
  replicas: 1
  selector:
    matchLabels:
      app: account-service
  template:
    metadata:
      labels:
        app: account-service
    spec:
      containers:
      - name: account-service
        image: account-service:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8080

        env:
        - name: CONFIG_PATH
          value: "./config/accountservice.toml"

        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"