bind_addr=":8082"

log_level="debug"
log_format="text"

kafka_groupid="account_service"
kafka_user_changed_topic="user.changed"

[store]
database_url="host=postgres-account-service port=5432 user=postgres password=1234 dbname=account_service_dev sslmode=disable"