CREATE TABLE balance (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,

    account UUID NOT NULL UNIQUE,

    balance NUMERIC(19, 2) NOT NULL DEFAULT 0
);

CREATE TABLE reserved (
    id BIGSERIAL PRIMARY KEY,

    account_id BIGINT NOT NULL,

    amount NUMERIC(19, 2) NOT NULL,

    idempotent UUID NOT NULL UNIQUE,

    CONSTRAINT fk_reserved_account
        FOREIGN KEY (account_id) REFERENCES balance(id)
);

CREATE INDEX idx_reserved_account ON reserved(account_id);
CREATE INDEX idx_reserved_idempotent ON reserved(idempotent);

CREATE USER debezium WITH PASSWORD 'dbz';

ALTER ROLE debezium WITH REPLICATION LOGIN;

GRANT CONNECT ON DATABASE transactional_orchestrator TO debezium;

GRANT USAGE ON SCHEMA public TO debezium;

GRANT SELECT ON ALL TABLES IN SCHEMA public TO debezium;

ALTER DEFAULT PRIVILEGES IN SCHEMA public
GRANT SELECT ON TABLES TO debezium;

CREATE PUBLICATION outbox_pub
FOR TABLE public.tbl_outbox;