CREATE TABLE tbl_balance (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,

    account UUID NOT NULL UNIQUE,

    balance NUMERIC(19, 2) NOT NULL DEFAULT 0
);

CREATE TABLE tbl_reserved (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,

    account_id BIGINT NOT NULL,

    amount NUMERIC(19, 2) NOT NULL,

    idempotent UUID NOT NULL,

    CONSTRAINT fk_reserved_account
        FOREIGN KEY (account_id) REFERENCES tbl_balance(id)
);

CREATE INDEX idx_reserved_idempotent_account_id
ON tbl_reserved (idempotent, account_id);

CREATE TABLE tbl_outbox (
    id UUID PRIMARY KEY,
    event_key VARCHAR(255) NOT NULL,
    category VARCHAR(50) NOT NULL,
    payload JSONB NOT NULL,
    created_at TIMESTAMP NOT NULL
);

CREATE INDEX idx_outbox_event_key
ON tbl_outbox (event_key);

CREATE INDEX idx_outbox_category
ON tbl_outbox (category);

CREATE INDEX idx_outbox_created_at
ON tbl_outbox (created_at);

CREATE INDEX idx_reserved_account ON tbl_reserved(account_id);
CREATE INDEX idx_reserved_idempotent ON tbl_reserved(idempotent);

CREATE USER debezium WITH PASSWORD 'dbz';

ALTER ROLE debezium WITH REPLICATION LOGIN;

GRANT CONNECT ON DATABASE balance TO debezium;

GRANT USAGE ON SCHEMA public TO debezium;

GRANT SELECT ON ALL TABLES IN SCHEMA public TO debezium;

ALTER DEFAULT PRIVILEGES IN SCHEMA public
GRANT SELECT ON TABLES TO debezium;

CREATE PUBLICATION outbox_pub
FOR TABLE public.tbl_outbox;

SELECT * FROM pg_create_logical_replication_slot(
  'debezium_kafka_outbox_slot',
  'pgoutput'
);