apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-configmap
  namespace: microservices
data:
  redis.conf: |
    # Основные настройки
    appendonly yes
    save 60 1
    
    # Настройки памяти
    maxmemory 64mb
    maxmemory-policy allkeys-lru
    
    # Безопасность
    protected-mode yes
    
    # Производительность
    tcp-backlog 511
    timeout 0
    tcp-keepalive 300
    
    # Логирование
    loglevel notice
    
    # Количество баз данных
    databases 16
    
    # Настройки репликации (для будущего масштабирования)
    replica-read-only yes
    
    # Медленные логи
    slowlog-log-slower-than 10000
    slowlog-max-len 128