apiVersion: v1
kind: Secret
metadata:
  name: redis-secret
  namespace: microservices
type: Opaque
stringData:
  AUTH_PASSWORD: "Au1th$ecretP@sz163"
  GATEWAY_PASSWORD: "R4nd0mT0rngP@ssw0rd!XyZ"
  REDIS_URL_AUTH: "redis://auth:Au1th$ecretP@sz163@redis-service:6379/0"
  REDIS_URL_GATEWAY: "redis://gateway:R4nd0mT0rngP@ssw0rd!XyZ@redis-service:6379/0"
  users.acl: |
    user gateway on >R4nd0mT0rngP@ssw0rd!XyZ ~*request_rate_limiter* +@all
    user auth on >Au1th$ecretP@sz163 ~auth:* ~user:* +@all
    user default off