apiVersion: v1
kind: Secret
metadata:
  name: postgres-balance-secret
  namespace: microservices
type: Opaque
stringData:
  POSTGRES_USER: "postgres_balance"
  POSTGRES_PASSWORD: "password_postgres_balance"
  POSTGRES_DB: "balance"