apiVersion: v1
kind: Service
metadata:
  name: kafka1
  namespace: microservices
spec:
  selector:
    app: kafka
    broker-id: "1"
  ports:
  - name: broker
    port: 9092
    targetPort: 9092
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: kafka2
  namespace: microservices
spec:
  selector:
    app: kafka
    broker-id: "2"
  ports:
  - name: broker
    port: 9092
    targetPort: 9092
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: kafka3
  namespace: microservices
spec:
  selector:
    app: kafka
    broker-id: "3"
  ports:
  - name: broker
    port: 9092
    targetPort: 9092
  type: ClusterIP