apiVersion: apps/v1
kind: Deployment
metadata:
  name: transactionprocessor-service
  namespace: microservices
spec:
  replicas: 1
  selector:
    matchLabels:
      app: transactionprocessor-service
  template:
    metadata:
      labels:
        app: transactionprocessor-service
    spec:
      containers:
      - name: transactionprocessor-service
        image: transactionprocessor-service:latest
        imagePullPolicy: Never

        ports:
        - containerPort: 8080

        env:
        - name: CONFIG_PATH
          value: "./config/transactionprocessor.toml"

        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"