apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: microservices

type: Opaque

stringData:
  MONGO_INITDB_ROOT_USERNAME: root
  MONGO_INITDB_ROOT_PASSWORD: root123

  MONGO_APP_USERNAME: kafka_writer
  MONGO_APP_PASSWORD: secure_password