spring:
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      username: ${REDIS_USERNAME}
      password: ${REDIS_PASSWORD}

  application:
    name: gateway-service
  cloud:
    gateway:
      metrics:
        enabled: true
      observation:
        enabled: true
      default-filters:
        - StripPrefix=1
        - name: RequestRateLimiter
          args:
            key-resolver: "#{@smartKeyResolver}"
            redis-rate-limiter.replenishRate: 1
            redis-rate-limiter.burstCapacity: 1
      routes:
        - id: auth
          uri: ${URI_AUTH}
          predicates:
            - Path=/auth/**

        - id: transactional
          uri: ${URI_TRANSACTIONAL}
          #lb://transactional-orchestrator
          predicates:
            - Path=/transactional/**

        - id: account
          uri: ${URI_ACCOUNT}
          predicates:
            - Path=/account/**

auth:
  public-key: ${AUTH_PUBLIC_KEY}

gateway:
  issuer: gateway
  private-key: ${GATEWAY_PRIVATE_KEY}
  public-key: ${GATEWAY_PUBLIC_KEY}
  ttl: 300

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  endpoint:
    health:
      show-details: always
  metrics:
    tags:
      application: gateway-service
  prometheus:
    metrics:
      export:
        enabled: true
  tracing:
    sampling:
      probability: 1.0   # 100% (для dev)
  otlp:
    tracing:
      endpoint: ${URI_JAEGER}
#eureka:
#  client:
#    service-url:
#      defaultZone: ${URI_EUREKA}
#    register-with-eureka: true
#    fetch-registry: true

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level traceId=%X{traceId} spanId=%X{spanId} %logger - %msg%n"