global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "gateway-service"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["gateway-service:8080"]
  - job_name: "transactional-orchestrator"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["transactional-orchestrator:8080"]