CREATE TABLE tbl_transaction (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    from_account_id UUID NOT NULL,
    to_account_id UUID NOT NULL,
    amount NUMERIC(19,2) NOT NULL,
    idempotent UUID NOT NULL UNIQUE,
    type VARCHAR(50) NOT NULL,
    status VARCHAR(50) NOT NULL DEFAULT 'CREATED',
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    executed_at TIMESTAMP,
    owner_id BIGINT NOT NULL
);

CREATE UNIQUE INDEX idx_transaction_idempotent
ON tbl_transaction (idempotent);


CREATE TABLE tbl_outbox (
    id UUID PRIMARY KEY,
    event_key VARCHAR(255) NOT NULL,
    category VARCHAR(50) NOT NULL,
    payload JSONB NOT NULL,
    created_at TIMESTAMP NOT NULL
);

CREATE INDEX idx_outbox_event_key
ON tbl_outbox (event_key);

CREATE INDEX idx_outbox_category
ON tbl_outbox (category);

CREATE INDEX idx_outbox_created_at
ON tbl_outbox (created_at);

CREATE USER debezium WITH PASSWORD 'dbz';

ALTER ROLE debezium WITH REPLICATION LOGIN;

GRANT CONNECT ON DATABASE transactional_orchestrator TO debezium;

GRANT USAGE ON SCHEMA public TO debezium;

GRANT SELECT ON ALL TABLES IN SCHEMA public TO debezium;

ALTER DEFAULT PRIVILEGES IN SCHEMA public
GRANT SELECT ON TABLES TO debezium;

CREATE PUBLICATION outbox_pub
FOR TABLE public.tbl_outbox;