apiVersion: v1
kind: Secret
metadata:
  name: postgres-transactionprocessor-secret
  namespace: microservices
type: Opaque
stringData:
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "1234"
  POSTGRES_DB: "transaction_processor_dev"