bind_addr=":8084"

log_level="debug"
log_format="text"

kafka_groupid="transaction_processor"
kafka_transaction_topic="transaction"

[store]
database_url="host=localhost user=postgres password=1234 dbname=transaction_processor_dev sslmode=disable"