apiVersion: v1
kind: Secret
metadata:
  name: balance-secret
  namespace: microservices
type: Opaque
stringData:
  DB_HOST: postgres_balance
  DB_USERNAME: postgres
  DB_PASSWORD: "1234"
  BOOTSTRAP_SERVERS: kafka1:9092,kafka2:9092,kafka3:9092