bind_addr=":8080"

log_level="debug"
log_format="text"

redis_addr="redis:6379"
redis_username="auth"
redis_password="Au1th$ecretP@sz163"

[store]
database_url="host=postgres_auth_service port=5432 user=postgres password=1234 dbname=auth_service_dev sslmode=disable"