bind_addr=":8080"

log_level="debug"
log_format="text"

kafka_groupid="notification_service"
kafka_user_changed_topic="user.changed"
kafka_send_notify_topic="notification"

[store]
database_url="host=postgres_notification_service port=5432 user=postgres password=1234 dbname=notification_service_dev sslmode=disable"