apiVersion: batch/v1
kind: Job
metadata:
  name: transactionorchestrator-migration
  namespace: microservices
spec:
  backoffLimit: 3
  template:
    spec:
      restartPolicy: Never

      containers:
      - name: migrator
        image: postgres:16-alpine

        env:
        - name: PGPASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-transactionorchestrator-secret
              key: POSTGRES_PASSWORD

        command:
        - sh
        - -c
        - |
          echo "Waiting for Postgres..."

          until pg_isready -h postgres-transactionorchestrator-service -U postgres_transactional_orchestrator -d transactional_orchestrator; do
            sleep 2
          done

          echo "Running migrations..."

          PGPASSWORD=$PGPASSWORD psql \
            -h postgres-transactionorchestrator-service \
            -U postgres_transactional_orchestrator \
            -d transactional_orchestrator \
            -f /config/init.sql

        volumeMounts:
        - name: init
          mountPath: /config

      volumes:
      - name: init
        configMap:
          name: postgres-transactionorchestrator-init