apiVersion: v1
kind: Secret
metadata:
  name: postgres-transactionorchestrator-secret
  namespace: microservices
type: Opaque
stringData:
  POSTGRES_USER: "postgres_transactional_orchestrator"
  POSTGRES_PASSWORD: "password_postgres_transactional_orchestrator"
  POSTGRES_DB: "transactional_orchestrator"