apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-transactionorchestrator
  namespace: microservices
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-transactionorchestrator
  template:
    metadata:
      labels:
        app: postgres-transactionorchestrator
    spec:
      containers:
      - name: postgres
        image: postgres:16-alpine

        args:
          - "-c"
          - "wal_level=logical"
          - "-c"
          - "max_replication_slots=4"
          - "-c"
          - "max_wal_senders=4"

        ports:
        - containerPort: 5432

        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: postgres-transactionorchestrator-secret
              key: POSTGRES_USER

        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-transactionorchestrator-secret
              key: POSTGRES_PASSWORD

        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: postgres-transactionorchestrator-secret
              key: POSTGRES_DB

        volumeMounts:
        - name: data
          mountPath: /var/lib/postgresql/data

        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"

      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: postgres-transactionorchestrator-pvc