apiVersion: v1
kind: Service
metadata:
  name: postgres-transactionorchestrator-service
  namespace: microservices
spec:
  selector:
    app: postgres-transactionorchestrator
  ports:
  - port: 5432
    targetPort: 5432
  type: ClusterIP